# Generated by Django 5.0.6 on 2024-06-29 19:07

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('понедельник', 'понедельник'), ('вторник', 'вторник'), ('среда', 'среда'), ('четверг', 'четверг'), ('пятница', 'пятница'), ('суббота', 'суббота'), ('воскресенье', 'воскресенье')], max_length=100, verbose_name='Дни'),
        ),
    ]
